// =============================================================================
// signalEngine.ts — QA9-R3: live AI trade-signal performance tracking —
// in-memory signalHistory, bootstrapRealTimeSignals() (boot-time seed),
// recordGeneratedSignal() (shared with the Gemini trading-signals endpoint),
// updatePendingSignals() (evaluates pending signals against live prices via
// the assets refresh hook), and the /api/trading-signals endpoints
// (history + generate-manual). Extracted verbatim from server.ts
// (was 2718-2962, 5042-5132).
// =============================================================================
import { liveAssets } from "./assetsStore";
import type { Express } from "express";
import { requireAuth } from "./auth";
import { createLogger } from "./logger";

const log = createLogger("signalEngine");

// TYPES & IN-MEMORY RUNTIME FOR LIVE AI TRADE SIGNAL PERFORMANCE TRACKING
export interface SignalHistoryEntry {
  id: string;
  symbol: string;
  category: "crypto" | "stock";
  recommendation: "STRONG BUY" | "BUY" | "HOLD" | "SELL" | "STRONG SELL";
  confidence: number;
  // DATA-3: provenance label — "heuristic" (momentum rule on real 24h
  // change), "ai" (Gemini analysis), or "manual" (user-entered).
  source: "heuristic" | "ai" | "manual";
  entryPrice: number;
  currentPrice: number;
  tpPrice: number;
  slPrice: number;
  status: "PENDING" | "TARGET HIT (TP)" | "STOP LOSS (SL)";
  timestamp: string;
  timeframe: "intraday" | "daily" | "weekly";
}

// In-memory signal history (no persistence — values are honest and ephemeral)
let signalHistory: SignalHistoryEntry[] = [];

// DATA-3: honest heuristic confidence. Documented formula:
//   confidence = clamp(round(50 + |change24h| * 5), 50, 90)
// Rationale: a bootstrap "signal" is only a momentum heuristic on the REAL
// 24h change, so bigger |change| = stronger momentum = higher (never high)
// confidence; small moves are low-confidence HOLDs. No Math.random.
function heuristicConfidence(change24h: number): number {
  return Math.min(90, Math.max(50, Math.round(50 + Math.abs(change24h) * 5)));
}

// Real-time bootstrap function directly deriving values from live assets price actions.
// Documented momentum heuristic (DATA-3):
//   change > 3.5  → STRONG BUY;  change > 0.8  → BUY
//   change < -3.5 → STRONG SELL; change < -0.8 → SELL
//   otherwise     → HOLD
// Every bootstrap signal is labeled source:"heuristic" so the UI can show
// that it is a rule-based signal, not an AI one.
export function bootstrapRealTimeSignals() {
  signalHistory = []; // Reset completely! No hardcoded static values.
  
  if (!liveAssets || liveAssets.length === 0) return;

  liveAssets.forEach((asset) => {
    const change = asset.change24h || 0;
    let rec: "STRONG BUY" | "BUY" | "HOLD" | "SELL" | "STRONG SELL" = "HOLD";

    if (change > 3.5) {
      rec = "STRONG BUY";
    } else if (change > 0.8) {
      rec = "BUY";
    } else if (change < -3.5) {
      rec = "STRONG SELL";
    } else if (change < -0.8) {
      rec = "SELL";
    }

    recordGeneratedSignal(
      asset.symbol,
      asset.category,
      rec,
      heuristicConfidence(change),
      asset.price,
      "heuristic"
    );
  });
}

// Initialise the bootstrap immediately with live active prices
bootstrapRealTimeSignals();

// Helper to record a new live signal generated by either Gemini or Fallback models
export function recordGeneratedSignal(
  symbol: string,
  category: "crypto" | "stock",
  recommendation: "STRONG BUY" | "BUY" | "HOLD" | "SELL" | "STRONG SELL",
  confidence: number,
  price: number,
  source: "heuristic" | "ai" = "ai"
) {
  // DATA-3: timeframe is a documented deterministic default ("daily") for
  // system-generated signals — the old random timeframe pick was fabrication.
  const timeframe: "intraday" | "daily" | "weekly" = "daily";

  // DATA-3: documented fixed TP/SL model for system-generated signals (the
  // old Math.random ±5-9% / -3-5% jitter fabricated the levels):
  //   BUY:  TP = +5%, SL = -3%   (risk:reward ≈ 1 : 1.67)
  //   SELL: TP = -5%, SL = +3%
  //   HOLD: TP = +4%, SL = -3%   (monitoring band)
  let tpPrice = price;
  let slPrice = price;
  const isBuy = recommendation.includes("BUY");
  const isSell = recommendation.includes("SELL");

  if (isBuy) {
    tpPrice = price * 1.05;
    slPrice = price * 0.97;
  } else if (isSell) {
    tpPrice = price * 0.95;
    slPrice = price * 1.03;
  } else {
    // HOLD
    tpPrice = price * 1.04;
    slPrice = price * 0.97;
  }

  // Decimals formatting
  // FIX-ALL L5: use toFixed(8) for low-priced assets (price < 1.0, e.g.
  // SHIB/PEPE) so tpPrice/slPrice are not rounded to 0. Previously toFixed(4)
  // rounded 0.00001234 → 0.0000 → 0, which caused updatePendingSignals to
  // immediately mark these as "TARGET HIT (TP)" because currentPrice >= 0 is
  // always true. With 8 decimals, 0.00001234 → 0.00001234 (preserved).
  if (price > 100) {
    tpPrice = parseFloat(tpPrice.toFixed(2));
    slPrice = parseFloat(slPrice.toFixed(2));
  } else if (price >= 1.0) {
    tpPrice = parseFloat(tpPrice.toFixed(4));
    slPrice = parseFloat(slPrice.toFixed(4));
  } else {
    // Low-priced asset (SHIB, PEPE, etc.) — preserve 8 decimals.
    tpPrice = parseFloat(tpPrice.toFixed(8));
    slPrice = parseFloat(slPrice.toFixed(8));
  }

  const newSignal: SignalHistoryEntry = {
    id: `sig_${Date.now()}_${Math.random().toString(36).substring(2, 6)}`,
    symbol,
    category,
    recommendation,
    confidence,
    source,
    entryPrice: price,
    currentPrice: price,
    tpPrice,
    slPrice,
    status: "PENDING",
    timestamp: new Date().toISOString(),
    timeframe
  };

  signalHistory.unshift(newSignal);

  // Maintain memory array caps
  if (signalHistory.length > 200) {
    signalHistory = signalHistory.slice(0, 200);
  }

  return newSignal;
}

// Background matching engine evaluating pending signals against volatile prices
export function updatePendingSignals() {
  signalHistory.forEach((sig) => {
    if (sig.status !== "PENDING") return;
    
    const asset = liveAssets.find(a => a.symbol === sig.symbol);
    if (!asset) return;

    sig.currentPrice = asset.price;
    const isBuy = sig.recommendation.includes("BUY");
    const isSell = sig.recommendation.includes("SELL");

    if (isBuy) {
      if (asset.price >= sig.tpPrice) {
        sig.status = "TARGET HIT (TP)";
      } else if (asset.price <= sig.slPrice) {
        sig.status = "STOP LOSS (SL)";
      }
    } else if (isSell) {
      if (asset.price <= sig.tpPrice) {
        sig.status = "TARGET HIT (TP)";
      } else if (asset.price >= sig.slPrice) {
        sig.status = "STOP LOSS (SL)";
      }
    } else {
      // HOLD signals remain ACTIVE/PENDING until manually closed by the user.
      // Previously this branch randomly closed HOLD signals which fabricated
      // fake win/loss outcomes. HOLD signals intentionally have no TP/SL hit
      // criteria — they wait for the user to take action.
    }
  });
}


export function registerSignalRoutes(app: Express): void {
// Query signals list & recap stats endpoint
// SEC-3: requireAuth — signal history is per-user-adjacent analytics and was
// previously readable (and writable via generate-manual) by anonymous clients.
app.get("/api/trading-signals/history", requireAuth, (req, res) => {
  const { symbol, timeframe } = req.query;
  
  let filtered = [...signalHistory];
  if (symbol) {
    filtered = filtered.filter(s => s.symbol === String(symbol).toUpperCase().trim());
  }
  if (timeframe) {
    filtered = filtered.filter(s => s.timeframe === timeframe);
  }

  // Base aggregates
  const total = signalHistory.length;
  const completed = signalHistory.filter(s => s.status !== "PENDING");
  const totalTp = signalHistory.filter(s => s.status === "TARGET HIT (TP)").length;
  const totalSl = signalHistory.filter(s => s.status === "STOP LOSS (SL)").length;
  const totalPending = signalHistory.filter(s => s.status === "PENDING").length;

  // DATA-3/FUNC-18: winRate is null when no signal has COMPLETED yet — the
  // old defaults (75% / 80% / 75% / 70%) were fabricated. The frontend shows
  // "N/A" for null.
  const winRate = completed.length > 0 
    ? parseFloat(((totalTp / completed.length) * 100).toFixed(1)) 
    : null;

  // Granular Timeframe compilations (intraday, daily, weekly)
  const getTfRecapObj = (tf: "intraday" | "daily" | "weekly") => {
    const list = signalHistory.filter(s => s.timeframe === tf);
    const comp = list.filter(s => s.status !== "PENDING");
    const tp = list.filter(s => s.status === "TARGET HIT (TP)").length;
    const sl = list.filter(s => s.status === "STOP LOSS (SL)").length;
    const wr = comp.length > 0 ? parseFloat(((tp / comp.length) * 100).toFixed(1)) : null;

    return {
      total: list.length,
      tp,
      sl,
      pending: list.filter(s => s.status === "PENDING").length,
      winRate: wr
    };
  };

  return res.json({
    signals: filtered,
    metrics: {
      totalSignals: total,
      completedSignals: completed.length,
      totalTp,
      totalSl,
      totalPending,
      winRate,
      timeframeRecap: {
        intraday: getTfRecapObj("intraday"),
        daily: getTfRecapObj("daily"),
        weekly: getTfRecapObj("weekly")
      }
    }
  });
});

// --- 8. POST /api/trading-signals/generate-manual -------------------------
// Manual signal entry. Validates required fields and pushes to signalHistory.
app.post("/api/trading-signals/generate-manual", requireAuth, (req, res) => {
  try {
    const {
      symbol,
      direction,
      entryPrice,
      tpPrice,
      slPrice,
      timeframe,
      notes
    } = req.body || {};

    if (!symbol || !direction || entryPrice == null || tpPrice == null || slPrice == null) {
      return res.status(400).json({
        success: false,
        error: "Field wajib: symbol, direction, entryPrice, tpPrice, slPrice."
      });
    }

    const upperSymbol = String(symbol).toUpperCase().trim();
    // SEC-25-style guard: strict charset before the symbol is stored / used
    // for price lookups.
    if (!/^[A-Z0-9.\-]{2,20}$/.test(upperSymbol)) {
      return res.status(400).json({
        success: false,
        error: "Simbol hanya boleh huruf besar, angka, titik, dan strip (2-20 karakter)."
      });
    }
    const dir = String(direction).toUpperCase().trim() as
      "STRONG BUY" | "BUY" | "HOLD" | "SELL" | "STRONG SELL";
    const validDirs: ("STRONG BUY" | "BUY" | "HOLD" | "SELL" | "STRONG SELL")[] =
      ["STRONG BUY", "BUY", "HOLD", "SELL", "STRONG SELL"];
    if (!validDirs.includes(dir)) {
      return res.status(400).json({
        success: false,
        error: `Direction tidak valid. Pilihan: ${validDirs.join(", ")}`
      });
    }

    const entry = parseFloat(entryPrice);
    const tp = parseFloat(tpPrice);
    const sl = parseFloat(slPrice);
    if (!isFinite(entry) || !isFinite(tp) || !isFinite(sl)) {
      return res.status(400).json({
        success: false,
        error: "entryPrice, tpPrice, slPrice harus berupa angka yang valid."
      });
    }

    const tf: "intraday" | "daily" | "weekly" =
      timeframe === "weekly" ? "weekly" :
      timeframe === "daily" ? "daily" : "intraday";

    const asset = liveAssets.find(a => a.symbol === upperSymbol);
    const category: "crypto" | "stock" = asset?.category === "stock" ? "stock" : "crypto";

    const newSignal: SignalHistoryEntry = {
      id: `sig_manual_${Date.now()}_${Math.random().toString(36).substring(2, 6)}`,
      symbol: upperSymbol,
      category,
      recommendation: dir,
      confidence: 100, // user-submitted, treat as fully intentional
      source: "manual",
      entryPrice: entry,
      currentPrice: entry,
      tpPrice: tp,
      slPrice: sl,
      status: "PENDING",
      timestamp: new Date().toISOString(),
      timeframe: tf
    };

    signalHistory.unshift(newSignal);
    if (signalHistory.length > 200) {
      signalHistory = signalHistory.slice(0, 200);
    }

    return res.json({
      success: true,
      signal: newSignal,
      notes: notes || ""
    });
  } catch (err: any) {
    return res.status(500).json({ success: false, error: "Gagal memproses sinyal. Silakan coba lagi nanti." });
  }
});
} // end registerSignalRoutes

